name: Parallel test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 18 1 * *"
  workflow_dispatch:
    inputs:
      algorithm:
        description: Algorithm preset (Optional)
        required: false
      random_seed:
        description: Random seed (Optional)
        required: false

run-name: ${{ github.event_name == 'workflow_dispatch' && format('Manual run algorithm {0}, seed {1}', github.event.inputs.algorithm, github.event.inputs.random_seed) || '' }}

jobs:
  test:
    name: Parallel test of BDS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        algorithm: [cbds, pbds, rbds, pads, ds]
        include:
          - os: macos-15-intel
            python-version: "3.10"
            algorithm: cbds
          - os: macos-15-intel
            python-version: "3.10"
            algorithm: pbds
          - os: macos-15-intel
            python-version: "3.10"
            algorithm: rbds
          - os: macos-15-intel
            python-version: "3.10"
            algorithm: pads
          - os: macos-15-intel
            python-version: "3.10"
            algorithm: ds
        exclude:
          - os: macos-latest
            python-version: "3.10"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: python -m pip install -e .

      - name: Run parallel tests
        env:
          BDS_TEST_ALGORITHM: ${{ github.event.inputs.algorithm || matrix.algorithm }}
          BDS_TEST_SEED: ${{ github.event.inputs.random_seed }}
        run: python -m unittest tests.test_parallel
